/**
 * home/routes.js — public home-page data (mounted at /api/home).
 *
 * GET /api/home/hero → { stats, media, slogans } for the landing hero:
 *   - stats:   site totals (vods, live sessions, chat messages, users, weekly-active, live now)
 *   - media:   a shuffled mix of live streams + recent VODs + clips + pastes for the floating
 *              thumbnail collage (thumbnail, title, type, link). VOD/clip/paste rows come
 *              from OpenVibe.Media (short-cached); live streams stay local.
 *   - slogans: { audiences, quips } rotating hero copy. AI-generated by slogan-job (cached in
 *              site_settings), with a rich static fallback so the hero is always lively.
 */
'use strict';
const express = require('express');
const db = require('../db/database');
const media = require('../media-client');

const router = express.Router();
const SLOGAN_INTERVAL_MS = 6 * 60 * 60 * 1000; // must match slogan-job INTERVAL_MS

// ── Static fallback slogans (used until the AI job fills site_settings, or if AI is off) ──
const FALLBACK_AUDIENCES = [
    'IRL streamers', 'desktop gamers', 'digital nomads', 'van dwellers', 'tinkerers',
    'night-shift coders', 'urban explorers', 'thru-hikers', 'overlanders',
    'people who left Twitch', 'the terminally online', 'garage inventors', 'ham radio nerds',
    'lofi enjoyers', 'late-night philosophers', 'the chronically curious', 'weekend makers',
    'retro hardware freaks', 'anyone with a webcam and a dream', 'backyard astronomers',
    'keyboard warriors (literal)', 'off-grid dreamers', 'the beautifully unhinged',
];
const FALLBACK_QUIPS = [
    'No investors. No suits. Just vibes.',
    'The stream site that pays rent in good vibes.',
    'Open source and proud of it.',
    'Built in the open, for everyone.',
    'Your stream, your rules, your vibe.',
    "Corporate streaming? We don't know her.",
    'Low latency, high chaos.',
    'Go live in seconds — regret it in real time.',
    'Powered by caffeine and spite.',
    'The internet hangout everyone forgot they wanted.',
    'Clip it before it happens.',
    'Free to start, because gatekeeping is boring.',
    'Where the wifi is questionable and the community is not.',
    'Stream from a van. We support that lifestyle.',
    'One account. All of OpenVibe.',
];

function _shuffle(arr) {
    const a = arr.slice();
    for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; }
    return a;
}

// ── Short-cached Media content pools (avoid hammering openvibe.media per request) ──
let _mediaPool = { vods: [], clips: [], pastes: [], at: 0 };
const MEDIA_POOL_TTL_MS = 30_000;
async function _mediaContent() {
    if (Date.now() - _mediaPool.at < MEDIA_POOL_TTL_MS) return _mediaPool;
    const [vods, clips, pastes] = await Promise.all([
        media.listVods({ limit: 12 }).then(r => r?.vods || (Array.isArray(r) ? r : [])).catch(() => _mediaPool.vods),
        media.listClips({ limit: 12 }).then(r => r?.clips || (Array.isArray(r) ? r : [])).catch(() => _mediaPool.clips),
        media.listPastes({ limit: 12, visibility: 'public' }).then(r => r?.pastes || (Array.isArray(r) ? r : [])).catch(() => _mediaPool.pastes),
    ]);
    _mediaPool = { vods, clips, pastes, at: Date.now() };
    return _mediaPool;
}

function _pasteThumb(p) {
    if (p.screenshot_url) return media.publicUrl(p.screenshot_url);
    if (p.type === 'screenshot' && p.slug) return media.pasteRawUrl(p.slug);
    return null;
}

// Assemble the floating-collage media pool from every content type.
async function heroMedia() {
    const items = [];
    try {
        for (const s of (db.getLiveStreams() || []).slice(0, 8)) {
            items.push({ kind: 'live', title: s.title || 'Live now', thumbnail: s.thumbnail_url || null, href: `/@${s.username}`, username: s.username });
        }
    } catch { /* */ }
    try {
        const pool = await _mediaContent();
        for (const v of pool.vods) {
            items.push({ kind: 'vod', title: v.title || 'VOD', thumbnail: media.publicUrl(v.thumbnail_url) || media.thumbUrl(`vod-${v.id}`), href: `/vod/${v.id}`, username: v.username });
        }
        for (const c of pool.clips) {
            items.push({ kind: 'clip', title: c.title || 'Clip', thumbnail: media.publicUrl(c.thumbnail_url) || media.thumbUrl(`clip-${c.id}`), href: `/clip/${c.id}`, username: c.username });
        }
        for (const p of pool.pastes) {
            items.push({
                kind: 'paste', title: p.title || 'Paste', thumbnail: _pasteThumb(p),
                text: p.type === 'screenshot' ? null : String(p.content || '').slice(0, 140),
                href: `/p/${p.slug}`, username: p.username,
            });
        }
    } catch { /* */ }
    // AI "crazy moments" — daily-rotated standout frames from the AI memory data, deep-linking
    // to the exact VOD timestamp (populated by ai-moments-job).
    try {
        const hm = JSON.parse(db.getState('home_hero_moments') || '{}');
        for (const m of (hm.moments || [])) {
            if (!m || !m.vodId) continue;
            items.push({
                kind: 'moment', title: m.title || 'AI Moment', thumbnail: m.thumbnail || null,
                href: `/vod/${m.vodId}?t=${m.offset || 0}`, username: m.username,
            });
        }
    } catch { /* */ }
    // Interleave types so the collage isn't clumped, then shuffle for variety per request.
    return _shuffle(items).slice(0, 28);
}

// The full set of AI "crazy moment" frames (not subject to the collage shuffle/slice) — used
// for the full-bleed hero BACKGROUND that cross-fades through them.
function heroMoments() {
    try {
        const hm = JSON.parse(db.getState('home_hero_moments') || '{}');
        return (hm.moments || [])
            .filter(m => m && m.vodId && m.thumbnail)
            .map(m => ({ title: m.title || 'AI Moment', thumbnail: m.thumbnail, href: `/vod/${m.vodId}?t=${m.offset || 0}`, username: m.username }));
    } catch { return []; }
}

// An audience must be JUST the noun phrase that completes "Live streaming for ___" — strip any
// baked-in "(live) streaming for" / "for" prefix (some LLM outputs include it → "Live streaming
// for live streaming for nomads") and trailing punctuation.
function _cleanAudience(raw) {
    return String(raw == null ? '' : raw)
        .replace(/^\s*(live\s+)?streaming\s+for\s+/i, '')
        .replace(/^\s*for\s+/i, '')
        .replace(/^["'‘’“”\-\s]+|["'‘’“”\s]+$/g, '')
        .replace(/[.!,;:]+$/, '')
        .trim();
}

function heroSlogans() {
    let s = null;
    try {
        s = db.getState('home_hero_slogans');
        if (typeof s === 'string') s = JSON.parse(s);
    } catch { s = null; }
    const aiAud = (s && Array.isArray(s.audiences)) ? s.audiences.map(_cleanAudience).filter(a => a && a.length <= 60) : [];
    const aiQuips = (s && Array.isArray(s.quips)) ? s.quips.filter(q => q && String(q).length <= 120) : [];
    const hasAi = aiAud.length >= 4 || aiQuips.length >= 4;
    const updatedAt = (s && Number(s.updated_at)) || 0;
    // The slogan job regenerates every 12h; next_at is when the current batch is due to refresh.
    const nextAt = updatedAt ? updatedAt + SLOGAN_INTERVAL_MS : 0;
    // Purely AI once we have a batch; the static set is only the cold-start / AI-off default.
    return {
        audiences: _shuffle(Array.from(new Set(hasAi ? aiAud : FALLBACK_AUDIENCES))),
        quips: _shuffle(Array.from(new Set(hasAi ? aiQuips : FALLBACK_QUIPS))),
        ai: hasAi,
        updated_at: updatedAt || null,
        next_at: nextAt || null,
    };
}

// ── Media-side counters (VODs/clips/pastes live in OpenVibe.Media now — the
// local tables are empty post-split, so hero counts come from Media, cached).
let _mediaStats = { at: 0, data: null };
const MEDIA_STATS_TTL_MS = 5 * 60_000;
async function _mediaStatsCached() {
    if (Date.now() - _mediaStats.at < MEDIA_STATS_TTL_MS) return _mediaStats.data;
    try {
        _mediaStats = { at: Date.now(), data: await media.request('GET', '/stats') };
    } catch (err) {
        console.warn('[Home] Media stats unavailable:', err.message);
        _mediaStats.at = Date.now() - MEDIA_STATS_TTL_MS + 30_000;   // retry in 30s
    }
    return _mediaStats.data;
}

// GET /api/home/stats/series/:metric?days=30 — daily values behind a hero stat.
router.get('/stats/series/:metric', (req, res) => {
    const series = db.getHomeStatSeries(String(req.params.metric), req.query.days);
    if (!series) return res.status(404).json({ error: 'Unknown metric', metrics: db.HOME_SERIES_KEYS });
    res.set('Cache-Control', 'public, max-age=120');
    res.json(series);
});

async function heroStats() {
    const stats = { ...db.getHomeStats() };
    const m = await _mediaStatsCached();
    if (m) {
        stats.vods = m.vods;
        stats.clips = m.clips;
        stats.pastes = m.pastes;
        stats.pasteImages = m.pasteImages;
        stats.pasteText = m.pasteText;
        stats.streamHours = Math.round((m.durationSeconds || 0) / 3600);
        stats.recent = { ...stats.recent, vods: m.recent?.vods, clips: m.recent?.clips, hours: m.recent?.hours };
    }
    // Site-wide OpenCoins sit next to channel points on the board: one is the network-wide
    // currency people earn everywhere, the other is per-channel. The ledger lives on
    // OpenVibe.Network, so this is a cached internal call that is allowed to come back empty.
    try {
        const c = await require('../monetization/wallet-client').networkCoinStats();
        if (c) {
            stats.coinsEarned = c.earned;
            stats.coinsSpent = c.spent;
            stats.coinsCirculating = c.circulating;
            stats.coinHolders = c.holders;
        }
    } catch { /* the board is better off missing four chips than failing */ }
    return stats;
}

// ── GET /api/home/stats-live ────────────────────────────────────────
// Just the numbers the hero strip shows, so the home page can keep them current without
// re-fetching the whole hero payload (slogans, collage, moments) every few seconds. The
// underlying stats are memoised for 30s already; this adds a short cache of its own so a
// roomful of open tabs costs one computation, not one each.
let _liveStats = { at: 0, data: null };
router.get('/stats-live', (req, res) => {
    try {
        res.set('Cache-Control', 'public, max-age=5');
        if (_liveStats.data && Date.now() - _liveStats.at < 5000) return res.json(_liveStats.data);
        const s = db.getHomeStats();
        const data = {
            liveNow: s.liveNow, viewersNow: s.viewersNow, weeklyActive: s.weeklyActive,
            users: s.users, weeklyVisitors: s.weeklyVisitors, anons: s.anons, chatMessages: s.chatMessages,
            streamers: s.streamers, hoursWatched: s.hoursWatched,
            // The 7-day deltas the hero chips show under their numbers. Same shape as the full
            // board's `recent`, trimmed to the four that have one.
            recent: {
                users: s.recent?.users, anons: s.recent?.anons,
                messages: s.recent?.messages, hours: s.recent?.hours,
            },
        };
        _liveStats = { at: Date.now(), data };
        res.json(data);
    } catch (err) {
        res.status(500).json({ error: 'stats unavailable' });
    }
});

router.get('/hero', async (req, res) => {
    try {
        res.set('Cache-Control', 'public, max-age=20');
        const stats = await heroStats();
        // 24h viewer trend for the hero sparkline (sampled every 5 min by the sampler).
        try { stats.viewerTrend = db.getViewerTrend(24, 48); } catch { stats.viewerTrend = []; }
        res.json({ stats, media: await heroMedia(), moments: heroMoments(), slogans: heroSlogans() });
    } catch (err) {
        console.error('[Home] hero error:', err.message);
        res.status(500).json({ error: 'Failed to load hero' });
    }
});

// ── Star of OpenVibe: one featured streamer, spotlighted on the home page ──────────
// Picked by the `star_streamer` site setting (falls back to STAR_STREAMER in the env).
// Ships the bio in its own language AND in English for non-English streamers, plus the
// live stream (stream-card shape) when they're on. Cached ~20s.
let _starCache = { at: 0, key: '', data: null };
router.get('/star', async (req, res) => {
    try {
        res.set('Cache-Control', 'public, max-age=20');
        const config = require('../config');
        let uname = '';
        try { uname = String(db.getSetting('star_streamer') || '').trim(); } catch { uname = ''; }
        if (!uname) uname = String(config.starStreamer || '').trim();
        if (!uname) return res.json({ star: null });
        if (Date.now() - _starCache.at < 20_000 && _starCache.key === uname.toLowerCase() && _starCache.data) return res.json(_starCache.data);

        const user = db.getUserByUsername(uname);
        if (!user) return res.json({ star: null });
        const i18n = require('../i18n/translate');
        const channel = db.getChannelByUserId(user.id) || {};
        const code = i18n.channelLanguage(user.id);
        const live = (db.getLiveStreams() || []).find(s => s.user_id === user.id) || null;
        let liveSafe = null;
        if (live) { const { managed_stream_key, stream_key, ...safe } = live; liveSafe = safe; }
        const bio = String(user.bio || '').trim();
        let bio_en = null;
        if (bio && code !== 'en') { try { bio_en = await i18n.translate(bio, { from: code, to: 'en', context: 'bio' }); } catch { bio_en = null; } }
        let follower_count = null;
        try { follower_count = typeof db.getFollowerCount === 'function' ? db.getFollowerCount(user.id) : null; } catch { follower_count = null; }
        let last_stream = null;
        try { last_stream = (db.getRecentStreams(60) || []).find(s => s.user_id === user.id) || null; } catch { last_stream = null; }
        const data = {
            star: {
                username: user.username, display_name: user.display_name || user.username,
                avatar_url: user.avatar_url || null, profile_color: user.profile_color || null,
                bio, bio_en, language: { code, name: i18n.langName(code), flag: i18n.langFlag(code) },
                ai_overview: channel.ai_overview || null, category: channel.ai_category || channel.category || null,
                follower_count, live: liveSafe,
                last_live_at: live ? null : (last_stream && (last_stream.ended_at || last_stream.started_at)) || null,
                pick: (() => {
                    try {
                        const p = require('./star-job').loadPick();
                        if (p && String(p.username || '').toLowerCase() === user.username.toLowerCase()) return { headline: p.headline || null, reason: p.reason || null, picked_at: p.picked_at || null, next_at: p.next_at || null, by: p.by || null };
                    } catch { /* */ }
                    return null;
                })(),
                rotates: !String(db.getSetting('star_streamer_pinned') || '').trim(),
            },
        };
        _starCache = { at: Date.now(), key: uname.toLowerCase(), data };
        res.json(data);
    } catch (err) {
        console.error('[Home] star error:', err.message);
        res.status(500).json({ error: 'Failed to load star streamer' });
    }
});

// ── Community pulse: goals near completion, latest activity, weekly leaders,
// AI moment showcase, and the newest shipped update. Cached ~30s server-side.
let _pulseCache = { at: 0, data: null };
router.get('/pulse', async (req, res) => {
    try {
        res.set('Cache-Control', 'public, max-age=30');
        if (Date.now() - _pulseCache.at < 30_000 && _pulseCache.data) return res.json(_pulseCache.data);
        const pulse = db.getHomePulse();
        pulse.moments = heroMoments().slice(0, 10);
        pulse.latestUpdate = _latestUpdate();
        _pulseCache = { at: Date.now(), data: pulse };
        res.json(pulse);
    } catch (err) {
        console.error('[Home] pulse error:', err.message);
        res.status(500).json({ error: 'Failed to load pulse' });
    }
});

// Newest git commit = the latest shipped update (built-in-the-open hero one-liner).
// The newest shipped commit, shown as a one-liner in the hero.
//
// This used to shell out with execSync on the request path. That blocks the entire event loop —
// every other request on the box waits — for up to the 4s timeout, and because the cache was only
// written after the call returned, a burst of first-loads after a deploy all queued behind their
// own separate git process. Now the refresh happens off the request path and readers only ever
// get whatever was last resolved.
let _updateCache = { at: 0, data: null, running: false };
function _refreshLatestUpdate() {
    if (_updateCache.running) return;
    _updateCache.running = true;
    require('child_process').execFile(
        'git', ['--no-pager', 'log', '--pretty=format:%h||%s||%aI', '-1'],
        { cwd: require('path').join(__dirname, '../..'), encoding: 'utf8', timeout: 4000 },
        (err, stdout) => {
            _updateCache.running = false;
            _updateCache.at = Date.now();
            if (err) return;
            const [short, subject, date] = String(stdout).trim().split('||');
            _updateCache.data = subject ? { short, subject, date } : null;
        }
    );
}
function _latestUpdate() {
    if (Date.now() - _updateCache.at >= 5 * 60_000) _refreshLatestUpdate();   // never awaited
    return _updateCache.data;
}
// Resolve it once at startup so the very first home load already has it.
setTimeout(_refreshLatestUpdate, 1500).unref?.();

// ── "While you were away" / "Lately on OpenVibe" digest — for everyone ────────
// ?since=<ISO> (the client remembers its own last visit; anonymous / first visit → last 48h).
// Site-wide activity since then: who's live, who streamed (followed channels first for signed-in
// users), the numbers, and the hottest Arena mic lines.
const { requireAuth, optionalAuth } = require('../auth/auth');
router.get('/digest', optionalAuth, (req, res) => {
    try {
        const now = Date.now();
        let sinceMs = req.query.since && !Number.isNaN(Date.parse(req.query.since)) ? Date.parse(req.query.since) : now - 48 * 3600 * 1000;
        sinceMs = Math.max(now - 14 * 24 * 3600 * 1000, Math.min(sinceMs, now - 6 * 3600 * 1000));   // 6h … 14d window
        const since = new Date(sinceMs).toISOString();
        const sinceSql = since.replace('T', ' ').slice(0, 19);
        const uid = req.user ? req.user.id : null;
        const followed = new Set(uid ? (db.all('SELECT streamer_id FROM follows WHERE follower_id = ?', [uid]) || []).map(r => r.streamer_id) : []);
        const liveNow = (db.all(`SELECT u.id AS user_id, u.username, u.display_name, u.avatar_url, u.profile_color, s.title, s.viewer_count, s.started_at
            FROM streams s JOIN users u ON u.id = s.user_id WHERE s.is_live = 1 AND COALESCE(u.is_banned, 0) = 0
            ORDER BY s.viewer_count DESC, s.started_at DESC LIMIT 10`) || []).map(r => ({ ...r, followed: followed.has(r.user_id) }));
        const liveIds = new Set(liveNow.map(r => r.user_id));
        const streamed = (db.all(`SELECT u.id AS user_id, u.username, u.display_name, u.avatar_url, u.profile_color,
                COUNT(s.id) AS sessions, MAX(s.started_at) AS last_at, MAX(COALESCE(s.peak_viewers, 0)) AS peak_viewers,
                ROUND(SUM(COALESCE(s.duration_seconds, CASE WHEN s.ended_at IS NOT NULL THEN (julianday(s.ended_at) - julianday(s.started_at)) * 86400 ELSE 0 END)) / 3600.0, 1) AS hours,
                (SELECT title FROM streams t WHERE t.user_id = u.id AND t.started_at >= ? ORDER BY t.started_at DESC LIMIT 1) AS last_title
            FROM streams s JOIN users u ON u.id = s.user_id
            WHERE s.started_at >= ? AND s.is_live = 0 AND COALESCE(u.is_banned, 0) = 0
            GROUP BY u.id ORDER BY hours DESC, last_at DESC LIMIT 14`, [sinceSql, sinceSql]) || [])
            .filter(r => !liveIds.has(r.user_id)).map(r => ({ ...r, followed: followed.has(r.user_id), recap_stream_id: (() => { try { const x = db.get('SELECT r.stream_id FROM stream_recaps r JOIN streams s ON s.id = r.stream_id WHERE r.user_id = ? AND s.started_at >= ? ORDER BY r.created_at DESC LIMIT 1', [r.user_id, sinceSql]); return x ? x.stream_id : null; } catch { return null; } })() }))
            .sort((a, b) => (b.followed - a.followed) || (b.hours - a.hours)).slice(0, 8);
        const one = (sql, params) => { try { return get(sql, params); } catch { return null; } };
        const get = (sql, params) => db.get(sql, params);
        const stats = {
            streams: Number((one('SELECT COUNT(*) AS n FROM streams WHERE started_at >= ?', [sinceSql]) || {}).n || 0),
            hours: Number((one(`SELECT ROUND(SUM(COALESCE(duration_seconds, CASE WHEN ended_at IS NOT NULL THEN (julianday(ended_at) - julianday(started_at)) * 86400 ELSE (julianday('now') - julianday(started_at)) * 86400 END)) / 3600.0, 1) AS h FROM streams WHERE started_at >= ?`, [sinceSql]) || {}).h || 0),
            chat_lines: Number((one("SELECT COUNT(*) AS n FROM chat_messages WHERE timestamp >= ? AND COALESCE(is_deleted, 0) = 0", [sinceSql]) || {}).n || 0),
            new_follows: Number((one('SELECT COUNT(*) AS n FROM follows WHERE created_at >= ?', [sinceSql]) || {}).n || 0),
            new_members: Number((one('SELECT COUNT(*) AS n FROM users WHERE created_at >= ?', [sinceSql]) || {}).n || 0),
            mic_moments: Number((one('SELECT COUNT(*) AS n FROM arena_mic_moments WHERE said_at >= ?', [sinceSql]) || {}).n || 0),
        };
        let hot = [];
        try {
            hot = (db.all(`SELECT m.text, m.quality, m.said_at, m.aimed_at, u.username, u.display_name FROM arena_mic_moments m JOIN users u ON u.id = m.user_id
                WHERE m.said_at >= ? AND m.quality >= 7 ORDER BY m.quality DESC, m.said_at DESC LIMIT 3`, [sinceSql]) || []);
        } catch { hot = []; }
        res.set('Cache-Control', uid ? 'private, max-age=30' : 'public, max-age=60');
        res.json({ since, signed_in: !!uid, liveNow, streamed, stats, hot });
    } catch (err) {
        console.error('[Home] digest error:', err.message);
        res.status(500).json({ error: 'Failed to load digest' });
    }
});

// ── Discover: what to watch instead when a channel is offline (or anywhere) ────────────
// ?channel=<username> excludes that streamer from the picks and finds "streamers like them".
// Live now, this week's hottest clips (site-wide), the latest after-show reports, the star of
// the day, and streamers in the same category who were live recently. Cached ~60s per channel.
const _discoverCache = new Map();
router.get('/discover', optionalAuth, async (req, res) => {
    try {
        const uname = String(req.query.channel || '').trim().toLowerCase();
        const hit = _discoverCache.get(uname);
        if (hit && Date.now() - hit.at < 60000) { res.set('Cache-Control', 'public, max-age=30'); return res.json(hit.data); }
        const me = uname ? db.getUserByUsername(uname) : null;
        const exclude = me ? me.id : null;
        const media = require('../media-client');
        const strip = (s) => { if (!s) return s; const { stream_key, managed_stream_key, ...rest } = s; return rest; };
        const live = (db.getLiveStreams() || []).filter(s => s.user_id !== exclude).slice(0, 6).map(strip);
        let clips = [];
        try {
            const co = await media.listClips({ order: 'views', limit: 40 });
            const all = (co?.clips || (Array.isArray(co) ? co : [])).filter(c => (c.status === 'ready' || !c.status) && (c.visibility == null || c.visibility === 'public') && (c.channel_user_id || c.user_id) !== exclude);
            const weekAgo = Date.now() - 7 * 86400000;
            const fresh = all.filter(c => Date.parse(String(c.created_at || '').replace(' ', 'T') + 'Z') >= weekAgo);
            clips = (fresh.length >= 4 ? fresh : all).slice(0, 8).map(c => ({ id: c.id, title: c.title, thumbnail_url: c.thumbnail_url ? media.publicUrl(c.thumbnail_url) : null, duration_seconds: c.duration_seconds || c.duration || 0, view_count: Number(c.view_count) || 0, username: c.streamer_username || c.channel_username || c.username || null, display_name: c.streamer_display_name || c.channel_display_name || c.display_name || null, created_at: c.created_at, fresh: fresh.length >= 4 }));
        } catch { clips = []; }
        let recaps = [];
        try { recaps = require('../recap/recap').listRecentRecaps(6, exclude); } catch { recaps = []; }
        let star = null;
        try {
            const pick = require('./star-job').loadPick();
            const su = pick && pick.username ? db.getUserByUsername(pick.username) : null;
            if (su && su.id !== exclude) star = { username: su.username, display_name: su.display_name || su.username, avatar_url: su.avatar_url || null, profile_color: su.profile_color || null, headline: pick.headline || null, reason: pick.reason || null, live: live.some(l => l.user_id === su.id) };
        } catch { star = null; }
        let similar = [];
        try {
            const cat = me ? (db.getChannelByUserId(me.id) || {}) : {};
            const category = cat.ai_category || cat.category || null;
            // Who is actually active: ranked by hours + sessions in the window (followers only as a
            // nudge, category only as a tiebreak), live people first. 14 days; widen to 30 only if
            // that leaves fewer than 3 names — nobody wants "live 29d ago" as a recommendation.
            const pick = (days) => (db.all(`SELECT u.id, u.username, u.display_name, u.avatar_url, u.profile_color, MAX(s.started_at) AS last_live_at, COUNT(s.id) AS sessions,
                    ROUND(SUM(COALESCE(s.duration_seconds, CASE WHEN s.ended_at IS NOT NULL THEN (julianday(s.ended_at) - julianday(s.started_at)) * 86400 ELSE 0 END)) / 3600.0, 1) AS hours,
                    (SELECT COUNT(*) FROM follows f WHERE f.streamer_id = u.id) AS followers,
                    (SELECT COALESCE(ch.ai_category, ch.category) FROM channels ch WHERE ch.user_id = u.id) AS category
                FROM streams s JOIN users u ON u.id = s.user_id
                WHERE s.started_at >= datetime('now', ?) AND COALESCE(u.is_banned, 0) = 0 AND u.id != COALESCE(?, -1)
                GROUP BY u.id HAVING hours >= 0.25 OR sessions >= 2
                ORDER BY last_live_at DESC LIMIT 40`, [`-${days} days`, exclude]) || []);
            let rows = pick(14);
            if (rows.length < 3) rows = pick(30);
            const score = (r) => (live.some(l => l.user_id === r.id) ? 1000 : 0)
                + Number(r.hours || 0) * 2 + Math.min(Number(r.sessions || 0), 10)
                + Math.min(Number(r.followers || 0), 50) * 0.2
                + (category && r.category === category ? 2 : 0)
                - Math.max(0, (Date.now() - Date.parse(String(r.last_live_at).replace(' ', 'T') + 'Z')) / 86400000) * 0.6;   // every idle day costs
            similar = rows.map(r => ({ ...r, live: live.some(l => l.user_id === r.id), same_category: !!(category && r.category === category), score: score(r) }))
                .sort((a, b) => b.score - a.score).slice(0, 8);
        } catch { similar = []; }
        const data = { channel: me ? { username: me.username, display_name: me.display_name || me.username } : null, live, clips, recaps, star, similar };
        _discoverCache.set(uname, { at: Date.now(), data });
        res.set('Cache-Control', 'public, max-age=30');
        res.json(data);
    } catch (err) {
        console.error('[Home] discover error:', err.message);
        res.status(500).json({ error: 'Failed to load discover' });
    }
});

// Admin: pick a new Star of OpenVibe right now (the job otherwise rotates daily).
router.post('/star/rotate', requireAuth, async (req, res) => {
    if (!req.user || req.user.role !== 'admin') return res.status(403).json({ error: 'Admin only' });
    try {
        const out = await require('./star-job').rotate({ force: true });
        _starCache = { at: 0, key: '', data: null };
        res.json(out);
    } catch (err) { res.status(500).json({ error: err.message }); }
});

// Sample the live viewer total every 5 minutes for the hero sparkline.
let _samplerTimer = null;
function startViewerSampler() {
    if (_samplerTimer) return;
    try { db.recordViewerSample(); } catch { /* */ }
    _samplerTimer = setInterval(() => { try { db.recordViewerSample(); } catch { /* */ } }, 5 * 60 * 1000);
    if (_samplerTimer.unref) _samplerTimer.unref();
    console.log('[Home] viewer sampler started (5m)');
}

module.exports = router;
module.exports.startViewerSampler = startViewerSampler;
module.exports.FALLBACK_AUDIENCES = FALLBACK_AUDIENCES;
module.exports.FALLBACK_QUIPS = FALLBACK_QUIPS;
