/**
 * home/routes.js — public home-page data (mounted at /api/home).
 *
 * GET /api/home/hero → { stats, media, slogans } for the landing hero:
 *   - stats:   site totals (vods, live sessions, chat messages, users, weekly-active, live now)
 *   - media:   a shuffled mix of live streams + recent VODs + clips + pastes for the floating
 *              thumbnail collage (thumbnail, title, type, link). VOD/clip/paste rows come
 *              from OpenVibe.Media (short-cached); live streams stay local.
 *   - slogans: { audiences, quips } rotating hero copy. AI-generated by slogan-job (cached in
 *              site_settings), with a rich static fallback so the hero is always lively.
 */
'use strict';
const express = require('express');
const db = require('../db/database');
const media = require('../media-client');

const router = express.Router();
const SLOGAN_INTERVAL_MS = 6 * 60 * 60 * 1000; // must match slogan-job INTERVAL_MS

// ── Static fallback slogans (used until the AI job fills site_settings, or if AI is off) ──
const FALLBACK_AUDIENCES = [
    'IRL streamers', 'desktop gamers', 'digital nomads', 'van dwellers', 'tinkerers',
    'night-shift coders', 'urban explorers', 'thru-hikers', 'overlanders',
    'people who left Twitch', 'the terminally online', 'garage inventors', 'ham radio nerds',
    'lofi enjoyers', 'late-night philosophers', 'the chronically curious', 'weekend makers',
    'retro hardware freaks', 'anyone with a webcam and a dream', 'backyard astronomers',
    'keyboard warriors (literal)', 'off-grid dreamers', 'the beautifully unhinged',
];
const FALLBACK_QUIPS = [
    'No ads. No investors. No suits. Just vibes.',
    'The stream site that pays rent in good vibes.',
    'Open source and proud of it.',
    'Built in the open, for everyone.',
    'Your stream, your rules, your vibe.',
    "Corporate streaming? We don't know her.",
    'Low latency, high chaos.',
    'Go live in seconds — regret it in real time.',
    'Powered by caffeine and spite.',
    'The internet hangout everyone forgot they wanted.',
    'Clip it before it happens.',
    'Free forever, because we forgot to add a paywall.',
    'Where the wifi is questionable and the community is not.',
    'Stream from a van. We support that lifestyle.',
    'One account. All of OpenVibe.',
];

function _shuffle(arr) {
    const a = arr.slice();
    for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; }
    return a;
}

// ── Short-cached Media content pools (avoid hammering openvibe.media per request) ──
let _mediaPool = { vods: [], clips: [], pastes: [], at: 0 };
const MEDIA_POOL_TTL_MS = 30_000;
async function _mediaContent() {
    if (Date.now() - _mediaPool.at < MEDIA_POOL_TTL_MS) return _mediaPool;
    const [vods, clips, pastes] = await Promise.all([
        media.listVods({ limit: 12 }).then(r => r?.vods || (Array.isArray(r) ? r : [])).catch(() => _mediaPool.vods),
        media.listClips({ limit: 12 }).then(r => r?.clips || (Array.isArray(r) ? r : [])).catch(() => _mediaPool.clips),
        media.listPastes({ limit: 12, visibility: 'public' }).then(r => r?.pastes || (Array.isArray(r) ? r : [])).catch(() => _mediaPool.pastes),
    ]);
    _mediaPool = { vods, clips, pastes, at: Date.now() };
    return _mediaPool;
}

function _pasteThumb(p) {
    if (p.screenshot_url) return media.publicUrl(p.screenshot_url);
    if (p.type === 'screenshot' && p.slug) return media.pasteRawUrl(p.slug);
    return null;
}

// Assemble the floating-collage media pool from every content type.
async function heroMedia() {
    const items = [];
    try {
        for (const s of (db.getLiveStreams() || []).slice(0, 8)) {
            items.push({ kind: 'live', title: s.title || 'Live now', thumbnail: s.thumbnail_url || null, href: `/@${s.username}`, username: s.username });
        }
    } catch { /* */ }
    try {
        const pool = await _mediaContent();
        for (const v of pool.vods) {
            items.push({ kind: 'vod', title: v.title || 'VOD', thumbnail: media.publicUrl(v.thumbnail_url) || media.thumbUrl(`vod-${v.id}`), href: `/vod/${v.id}`, username: v.username });
        }
        for (const c of pool.clips) {
            items.push({ kind: 'clip', title: c.title || 'Clip', thumbnail: media.publicUrl(c.thumbnail_url) || media.thumbUrl(`clip-${c.id}`), href: `/clip/${c.id}`, username: c.username });
        }
        for (const p of pool.pastes) {
            items.push({
                kind: 'paste', title: p.title || 'Paste', thumbnail: _pasteThumb(p),
                text: p.type === 'screenshot' ? null : String(p.content || '').slice(0, 140),
                href: `/p/${p.slug}`, username: p.username,
            });
        }
    } catch { /* */ }
    // AI "crazy moments" — daily-rotated standout frames from the AI memory data, deep-linking
    // to the exact VOD timestamp (populated by ai-moments-job).
    try {
        const hm = JSON.parse(db.getState('home_hero_moments') || '{}');
        for (const m of (hm.moments || [])) {
            if (!m || !m.vodId) continue;
            items.push({
                kind: 'moment', title: m.title || 'AI Moment', thumbnail: m.thumbnail || null,
                href: `/vod/${m.vodId}?t=${m.offset || 0}`, username: m.username,
            });
        }
    } catch { /* */ }
    // Interleave types so the collage isn't clumped, then shuffle for variety per request.
    return _shuffle(items).slice(0, 28);
}

// The full set of AI "crazy moment" frames (not subject to the collage shuffle/slice) — used
// for the full-bleed hero BACKGROUND that cross-fades through them.
function heroMoments() {
    try {
        const hm = JSON.parse(db.getState('home_hero_moments') || '{}');
        return (hm.moments || [])
            .filter(m => m && m.vodId && m.thumbnail)
            .map(m => ({ title: m.title || 'AI Moment', thumbnail: m.thumbnail, href: `/vod/${m.vodId}?t=${m.offset || 0}`, username: m.username }));
    } catch { return []; }
}

// An audience must be JUST the noun phrase that completes "Live streaming for ___" — strip any
// baked-in "(live) streaming for" / "for" prefix (some LLM outputs include it → "Live streaming
// for live streaming for nomads") and trailing punctuation.
function _cleanAudience(raw) {
    return String(raw == null ? '' : raw)
        .replace(/^\s*(live\s+)?streaming\s+for\s+/i, '')
        .replace(/^\s*for\s+/i, '')
        .replace(/^["'‘’“”\-\s]+|["'‘’“”\s]+$/g, '')
        .replace(/[.!,;:]+$/, '')
        .trim();
}

function heroSlogans() {
    let s = null;
    try {
        s = db.getState('home_hero_slogans');
        if (typeof s === 'string') s = JSON.parse(s);
    } catch { s = null; }
    const aiAud = (s && Array.isArray(s.audiences)) ? s.audiences.map(_cleanAudience).filter(a => a && a.length <= 60) : [];
    const aiQuips = (s && Array.isArray(s.quips)) ? s.quips.filter(q => q && String(q).length <= 120) : [];
    const hasAi = aiAud.length >= 4 || aiQuips.length >= 4;
    const updatedAt = (s && Number(s.updated_at)) || 0;
    // The slogan job regenerates every 12h; next_at is when the current batch is due to refresh.
    const nextAt = updatedAt ? updatedAt + SLOGAN_INTERVAL_MS : 0;
    // Purely AI once we have a batch; the static set is only the cold-start / AI-off default.
    return {
        audiences: _shuffle(Array.from(new Set(hasAi ? aiAud : FALLBACK_AUDIENCES))),
        quips: _shuffle(Array.from(new Set(hasAi ? aiQuips : FALLBACK_QUIPS))),
        ai: hasAi,
        updated_at: updatedAt || null,
        next_at: nextAt || null,
    };
}

// ── Media-side counters (VODs/clips/pastes live in OpenVibe.Media now — the
// local tables are empty post-split, so hero counts come from Media, cached).
let _mediaStats = { at: 0, data: null };
const MEDIA_STATS_TTL_MS = 5 * 60_000;
async function _mediaStatsCached() {
    if (Date.now() - _mediaStats.at < MEDIA_STATS_TTL_MS) return _mediaStats.data;
    try {
        _mediaStats = { at: Date.now(), data: await media.request('GET', '/stats') };
    } catch (err) {
        console.warn('[Home] Media stats unavailable:', err.message);
        _mediaStats.at = Date.now() - MEDIA_STATS_TTL_MS + 30_000;   // retry in 30s
    }
    return _mediaStats.data;
}

async function heroStats() {
    const stats = { ...db.getHomeStats() };
    const m = await _mediaStatsCached();
    if (m) {
        stats.vods = m.vods;
        stats.clips = m.clips;
        stats.pastes = m.pastes;
        stats.pasteImages = m.pasteImages;
        stats.pasteText = m.pasteText;
        stats.streamHours = Math.round((m.durationSeconds || 0) / 3600);
        stats.recent = { ...stats.recent, vods: m.recent?.vods, clips: m.recent?.clips, hours: m.recent?.hours };
    }
    return stats;
}

router.get('/hero', async (req, res) => {
    try {
        res.set('Cache-Control', 'public, max-age=20');
        const stats = await heroStats();
        // 24h viewer trend for the hero sparkline (sampled every 5 min by the sampler).
        try { stats.viewerTrend = db.getViewerTrend(24, 48); } catch { stats.viewerTrend = []; }
        res.json({ stats, media: await heroMedia(), moments: heroMoments(), slogans: heroSlogans() });
    } catch (err) {
        console.error('[Home] hero error:', err.message);
        res.status(500).json({ error: 'Failed to load hero' });
    }
});

// ── Community pulse: goals near completion, latest activity, weekly leaders,
// AI moment showcase, and the newest shipped update. Cached ~30s server-side.
let _pulseCache = { at: 0, data: null };
router.get('/pulse', async (req, res) => {
    try {
        res.set('Cache-Control', 'public, max-age=30');
        if (Date.now() - _pulseCache.at < 30_000 && _pulseCache.data) return res.json(_pulseCache.data);
        const pulse = db.getHomePulse();
        pulse.moments = heroMoments().slice(0, 10);
        pulse.latestUpdate = _latestUpdate();
        _pulseCache = { at: Date.now(), data: pulse };
        res.json(pulse);
    } catch (err) {
        console.error('[Home] pulse error:', err.message);
        res.status(500).json({ error: 'Failed to load pulse' });
    }
});

// Newest git commit = the latest shipped update (built-in-the-open hero one-liner).
let _updateCache = { at: 0, data: null };
function _latestUpdate() {
    if (Date.now() - _updateCache.at < 5 * 60_000) return _updateCache.data;
    try {
        const { execSync } = require('child_process');
        const raw = execSync(`git --no-pager log --pretty=format:'%h||%s||%aI' -1`,
            { cwd: require('path').join(__dirname, '../..'), encoding: 'utf8', timeout: 4000 });
        const [short, subject, date] = String(raw).trim().split('||');
        _updateCache = { at: Date.now(), data: subject ? { short, subject, date } : null };
    } catch { _updateCache = { at: Date.now(), data: null }; }
    return _updateCache.data;
}

// ── "While you were away" digest for returning users ─────────────────────────
// ?since=<ISO> (the client remembers its own last visit). Followed channels that
// are live right now + those that streamed since the last visit.
const { requireAuth } = require('../auth/auth');
router.get('/digest', requireAuth, (req, res) => {
    try {
        const since = req.query.since && !Number.isNaN(Date.parse(req.query.since))
            ? new Date(req.query.since).toISOString()
            : new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString();
        const liveNow = db.all(`SELECT DISTINCT u.username, u.display_name, u.avatar_url
            FROM follows f JOIN users u ON u.id = f.streamer_id
            JOIN streams s ON s.user_id = f.streamer_id AND s.is_live = 1
            WHERE f.follower_id = ?`, [req.user.id]) || [];
        const missed = db.all(`SELECT u.username, u.display_name, u.avatar_url,
                COUNT(s.id) AS sessions, MAX(s.started_at) AS last_at, MAX(s.title) AS last_title
            FROM follows f JOIN users u ON u.id = f.streamer_id
            JOIN streams s ON s.user_id = f.streamer_id AND s.started_at >= ? AND s.is_live = 0
            WHERE f.follower_id = ?
            GROUP BY f.streamer_id ORDER BY last_at DESC LIMIT 6`, [since, req.user.id]) || [];
        // Don't list a channel as "missed" when it's live right now — it's in liveNow.
        const liveSet = new Set(liveNow.map(x => x.username));
        res.json({ since, liveNow, missed: missed.filter(m => !liveSet.has(m.username)) });
    } catch (err) {
        console.error('[Home] digest error:', err.message);
        res.status(500).json({ error: 'Failed to load digest' });
    }
});

// Sample the live viewer total every 5 minutes for the hero sparkline.
let _samplerTimer = null;
function startViewerSampler() {
    if (_samplerTimer) return;
    try { db.recordViewerSample(); } catch { /* */ }
    _samplerTimer = setInterval(() => { try { db.recordViewerSample(); } catch { /* */ } }, 5 * 60 * 1000);
    if (_samplerTimer.unref) _samplerTimer.unref();
    console.log('[Home] viewer sampler started (5m)');
}

module.exports = router;
module.exports.startViewerSampler = startViewerSampler;
module.exports.FALLBACK_AUDIENCES = FALLBACK_AUDIENCES;
module.exports.FALLBACK_QUIPS = FALLBACK_QUIPS;
